### ISSUE TITLE
Please update the installation guide to include windows 11

### ISSUE THREAD

**Issue by Rechi86** [tooll3/t3#268]
Hi, it might be a smaller thing but please update the installation info:

On Windows 10 you also need …
-> should be on "Windows 10/11 you also need …"

I've ignored the windows 10 info and got stuck for a while :(

But know I finally got over it and now finallly can try your promising project!

**Comment by Rechi86** [comment]
Thanks for your reply. 
My message above was probably a bit misleading:
The problem for me was on my Windows 11 system I also needed to install the Windows Graphics Tools to get Tooll3 running,
but I kinda ignored this info for quite some time because it explicitly said "on Windows 10 you also need Windows Graphics Tools".
I don't want to be pedantic but I almost gave up on this amazing tooll, and with this small change other user could be saved from a similar fate.

**Comment by sense-amr** [comment]
The General installation requirements are that Windows Graphics Tools needs to be enabled.. regardless of windows 10 or 11..

**Comment by sense-amr** [comment]
you dont need to give up the instructions for building your own build or just running using the downloadable standalone released version are clearly stated in the Installation Guide .. 
if you needed any further assistance and use Discord feel free to ask questions in the #installation-and-setup section of the discord channels ..

**Comment by Rechi86** [comment]
Thanks for your message. Like I said for me the installation worked in the end (and I'm already diving into the programm) and I've also used the discord channel already successfully for some other questions. 
It was just a thought that maybe other new users could stuble over that point as well. I will close the issue, thanks for your info.

**Comment by pixtur** [comment]
Thanks for letting us know. The installation guide could definitely be improved and combined with an updated video tutorial. I removed the win10 reference to make clearer that the graphics tools are also required for win11.

Please don't hesitate to add more issues regarding the documentation or reaching out on discord. Feedback like yours really helps us to improve that side of T3.
