### ISSUE TITLE
Start a Player at Fullscreenmode

### ISSUE THREAD

**Issue by KurtKomell** [tooll3/t3#270]
I would like to have a version of Tooll3 as a standalone player. So that I can start in fullscreen mode for an installation without having to make any entries. That would be very helpful. Maybe you can also tell me where in the code I can find the appropriate settings so that I can program it myself. Many thanks.

**Comment by pixtur** [comment]
Interesting. Can you elaborate on that? What to mean by " not any entries".

For an installation you should be able to export your project as an executable with the overhead of the editor... It will start in fullscreen mode by default. Also see: https://github.com/tooll3/t3/wiki/ExportingExecutables

**Comment by KurtKomell** [comment]
Thank You very much thats what Iam looking for. Great.
