### ISSUE TITLE
Standalone Dependencies Not copied to Export Directory

### ISSUE THREAD

**Issue by sense-amr** [tooll3/t3#274]
I am using the latest version of Tooll 3.6.1 with the last posted branch dev commit ..

When making an Export Executable with the standalone version .. the required dependencies .. are not copied to the Export directory and hence the Player fails.. 

The Export folder shows the following .. 

![image](https://github.com/tooll3/t3/assets/1504019/34b8316d-4d84-4e5c-b079-f78a4926eb04)

copying the following dependencies manually does work

![image](https://github.com/tooll3/t3/assets/1504019/8f1a283f-5eba-4568-99cd-e2cbba0c20b6)
and ```Svg.dll``` is already copied.. 

The above method of copying the dependencies to the Exported folder.. works for any kind of Exectuable that does NOT include PlayVideo .. 

A Graph Executable export containing PlayVideo will not work .. regardless of if the dependencies are copied or not ..

**Comment by pixtur** [comment]
Thanks for reporting. Should be fix on the dev branch.
