### ISSUE TITLE
(minor/usability) clicking "I know what I am doing" does not result in expected action

### ISSUE THREAD

**Issue by teadrinker** [tooll3/t3#288]
When opening a lib operator, it shows a warning (which is great).
Then the next time you to open a lib operator, you get straight inside.
 
However I feel the expected behaviour is that if I click "I know what I am doing", I should not have to repeat the action manually.

**Comment by pixtur** [comment]
I know the UX is not ideal, but I quickly looked into this and couldn't find an easy fix for this.

**Comment by ylmrx** [comment]
I think the repeated "I know what I'm doing" is the desirable behavior (but we could have a user setting "I really know what I'm doing", which disable all of these warnings)

wdyt ?

**Comment by pixtur** [comment]
Fixed with PR
