### ISSUE TITLE
README.md still have old link to documentation

### ISSUE THREAD

**Issue by newemka** [tooll3/t3#297]
Old link to documentation (https://github.com/still-scene/t3/wiki/user-interface) needs to be replaced by https://github.com/tooll3/t3/wiki/T3UserInterface

Installation guide (https://github.com/still-scene/t3/wiki/Installation) there is an automatic redirection to https://github.com/tooll3/t3/wiki/Installation

**Comment by pixtur** [comment]
Thanks for pointing out: Fixed with 78409b52426fdba09649234f39fa086d002d66a8
