### ISSUE TITLE
DrawPointsShaded and BlendGradients have some missing parameters while in Focus Mode

### ISSUE THREAD

**Issue by newemka** [tooll3/t3#298]
![image](https://github.com/tooll3/t3/assets/3755089/5eef2d35-9fdd-4d47-b2d3-f35df7b30ff2)

I spotted how to fix it, these parameters have MultiInputSlot in their .cs file 
 public readonly InputSlot<int> BlendMode = new MultiInputSlot<int>();

**Comment by pixtur** [comment]
Fix in d658eba01e748f0a517d465deb7b9b38b5dddb6e
