### ISSUE TITLE
"Optics Compensation" Effect

### ISSUE THREAD

**Issue by alyfreym** [tooll3/t3#299]
Cool optics compensation effect from After Effects 

I wrote my code in OpenGL but it doesn't work as expected.  Code attached below. 
I use Brown's Distortion Model. And I thins it is work like Barrel Distortion..
[OpticsCompensation Shader.txt](https://github.com/tooll3/t3/files/12834237/OpticsCompensation.Shader.txt)

this effect have 
1 - FOV. Field of view from 0 to 180
2 - FOV Orientation (Horizontal, Vertical, Diagonal) 

My result with FOV 120 
![example_my](https://github.com/tooll3/t3/assets/29518174/27651786-c48d-4dfd-92c2-c92025f0367e)

And animation from After Effects 
FOV animated from 0 to 180 with Horizontal orientation. Video example below

https://github.com/tooll3/t3/assets/29518174/f3450125-cd91-410b-b326-eefa70a459e5

**Comment by pixtur** [comment]
Huh? It's completed? How?
