### ISSUE TITLE
(Minor issue) Confusing TriggerAnim type "Kick"

### ISSUE THREAD

**Issue by teadrinker** [tooll3/t3#300]
The Kick trigger type seems to reverse start/end values and it also resets to start value if retriggered very briefly (like a single frame? however, at least in the editor, it's shown randomly), resulting in glitchy animation. 

![T3Editor_23-10-09__13-14-16](https://github.com/tooll3/t3/assets/678065/741fbcad-8456-47a4-89d8-28a32866b7fa)

This probably has some use case that I don't understand, but I tried to use it to animate scale to a "kick" in the soundtrack and it did not work well

**Comment by pixtur** [comment]
Hi @teadrinker . Thank you for that feedback. The title of that curve leave much to ask for, indeed. It is basically a "Saw"  (e.g. a progressing going from 1 to 0). But different to saw it starts with 0. This makes is useful for things like white flashes. With a saw-animation the screen would always be bright at position 0.

But I can seed that it's strange that it goes back to zero... I can look into that.

**Comment by pixtur** [comment]
I improved the behaviour with b4e981fda81cad3f69ace600e21a5e7de77faa1b
