### ISSUE TITLE
IntValue operator does not update current value in UI

### ISSUE THREAD

**Issue by H445** [tooll3/t3#305]
The IntValue operator does not show the current Int Value being passed to it

**To Reproduce**
1. Create 2 IntValue operators
2. Attach one input to the output of the other
3. Change the sender IntValue
4. See the receiving IntValue operator does not update to reflect the current IntValue in the UI. The operator does recognize the change, just does not display.

**Expected behavior**
The receiving IntValue operator should display its current value

**Screenshots**
![IntValue](https://github.com/tooll3/t3/assets/40644547/20a5f969-e0e2-4392-9684-01b1f23ee00d)

**Comment by ylmrx** [comment]
was fixed in 5df73aa
