### ISSUE TITLE
Integrated + Other Gpu setup problem to start

### ISSUE THREAD

**Issue by llama-jeff** [tooll3/t3#312]
Hi! How are you? I'm really into the tool, but can't run it and couldn't enter the discord to do a question. I use a two gpu setup, a integrated and a rtx2060, followed the instructions and I receive a error.

I tried to find something useful in the files where I can change the gpu and also tried to change it in the graphics setting in widows to force the software to use the rtx, but no luck.

The Error:
"We are sorry but your graphics hardware might not be capable of running Tooll2 HRESULT: [0x887A002D], Module: [SharpDX.DXGI], ApiCode:[DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing]"

 - OS: Windows 10
 - Version:10.0.19045
 - Vega 8 (Ryzen 3400G) and RTX 2060

![image](https://github.com/tooll3/t3/assets/20527966/13fe5599-2065-4131-8d55-2226d6513980)

**Comment by ylmrx** [comment]
https://github.com/tooll3/t3/wiki/Installation you seem to be missing the "windows graphic tools"

**Comment by pixtur** [comment]
Yes. The upcoming version v3.8 has a warning dialog dedicated to that with a help like how to a microsoft help that will guide you through the setup.

**Comment by llama-jeff** [comment]
weird, I activated it, I'll try again and update here
