### ISSUE TITLE
Record a video

### ISSUE THREAD

**Issue by Blossantrape** [tooll3/t3#315]
Please add an option to record the animation.
This is very lacking. The solution for me so far is to record the screen via OBS.

**Comment by pixtur** [comment]
hi @Blossantrape  are you referring to capturing realtime interactions? For rendering animations you could use "Window -> Render Video".

**Comment by Blossantrape** [comment]
hi @pixtur . Thanks for the reply. I'm sorry I didn't notice this tool earlier. 
The option is really great. Now it will be much more interesting and convenient to record animations.
