### ISSUE TITLE
Change particles close to the camera from shrinking to fading out

### ISSUE THREAD

**Issue by ScreenDream** [tooll3/t3#319]
**Describe the bug**
Currently, 'DrawBillboards' particles that get close to the camera shrink in size to zero.
That is very irritating, since it creates the impression of them suddenly moving away from the camera.
The brain is getting the wrong message.

**Expected behavior**
Either fade them out via Alpha blending or make it optional, since in some cases one may actually want things to 'pop' away when moving through the camera position.   

I can provide more info if necessary.

Thank you very much!!! :-)

**Comment by newemka** [comment]
I will take care of this

**Comment by newemka** [comment]
Here is how it looks now. 
https://github.com/tooll3/t3/assets/3755089/5ddd8b00-6944-4170-92c8-aca43274f393

**Comment by ScreenDream** [comment]
Cool.
I still think it should be optional but this is very usable.

Cool, thanks!

**Comment by newemka** [comment]
I agree with you, that's why I added a Bool parameter "TooCloseFadeOut", the fading out is only working if the parameter is set to true.

**Comment by ScreenDream** [comment]
Ha - no points for me for only watching the video in small size and not noticing the parameter.
Awesome! :-)

**Comment by pixtur** [comment]
Thanks for the fix, @newemka
