### ISSUE TITLE
DrawImageMosaic Crash

### ISSUE THREAD

**Issue by Voyager92** [tooll3/t3#337]
**Describe the bug**
[DrawImageMosaic] isnt working - either its crashing T3 or not updating texture operator 
![crasj](https://github.com/tooll3/t3/assets/64232750/7762463e-825d-4dac-b35c-71766c5d0f9d)

 - Version: 3.8.2

**Screenshots**
![sen2](https://github.com/tooll3/t3/assets/64232750/452b165e-feb9-4467-9d6b-1117751962bc)
![sense1](https://github.com/tooll3/t3/assets/64232750/db7af682-91b8-4766-a67a-7619f836af29)

**Comment by pixtur** [comment]
Thanks for reporting.
Fixed on dev-branch.
