### ISSUE TITLE
UI scale setting can make Tooll unusable (breaking user conf)

### ISSUE THREAD

**Issue by ylmrx** [tooll3/t3#341]
**Describe the bug**

Trying to enter a ui_scale below 1.0 lead the user to type '0' or '.' which tooll will interpret as 0 and entirely break its UI doing so.

**Please complete the following information):**
 - OS: windows11 (should affect all systems)
 - Graphics card and resolution: irrelevant

**To Reproduce**

1. go to settings > interface > ui scale
2. Select the field, start typing "0.75" or ".75"
3. Tooll breaks upon the 1st character, won't accept more input, and the ui scale-out beyond anything visible. 

**Expected behavior**

Tooll should let the user type the value they intend and parse it correctly.

**Additional context**

#340 fixes this

**Comment by pixtur** [comment]
Excellent report and great fix. I left a little change request on the PR.
