### ISSUE TITLE
Image of SoundTrack doesn't match with the music 

### ISSUE THREAD

**Issue by newemka** [tooll3/t3#374]
The image of the sound track is twice the size of the music 

 - OS: Win 10
 - Version: 3.9.1 

**To Reproduce**
1. Open a project 
2. got to Project settings 
3. load a sound track
4. use the play button 
5. all is fine
6. go back to project settings
7. load an other sound track - the image in the timeline is updated but it has the size of the previous sound track 
8. hit the play button - we still hear the previous sound track 
9. we need to go back to project settings and hit the Reload button then when we play the new sound track is playing fine and the image has the right size

10. now for Audio Source if we switch to an external device 
11. then back to Audio Source Project Sound Track 
12. now the image of the sound track is twice the size of the music 
13. the reload button doesn't help in this case 
14. Restart Tooll to get the right image size

**Expected behavior**
the image of the sound track should always match with the audio,  

**Screenshots**

https://github.com/tooll3/t3/assets/3755089/36e9f220-ab37-4e8b-a5a6-768bfade7744

**Comment by pixtur** [comment]
Thanks for reporting! With the concise steps to reproduce this, I was finally able to fix it.
