### ISSUE TITLE
MIDIInput not responding to trigger when Control is assigned by an input value in Tooll v3.9

### ISSUE THREAD

**Issue by JosebaBeristain** [tooll3/t3#384]
In Toolls 3.9.1 the <MidiInput> operator is not sending any trigger value (bool output) if the value for the "Control" parameter is assigned from an imput Integer. This works properly on v 3.8.2.1

You can see it in this vídeo:

https://github.com/tooll3/t3/assets/161488670/21072135-55ca-42c1-9189-bda35c0976fe

**Please complete the following information):**
 - OS: Windows
 - Version: 3.9.1
 - Graphics card and resolution: N/A

**To Reproduce**
1. Use  MIDIInput operator
2. After configuring it (controller name, Control number, etc.) check that bool output is sending the trigger signal
3. Now, create an intValue and connect it to Control paramenter
4. Now, the MIDIInput is not triggering anumore.

**Expected behavior**
The behavior should be the same in the Control values is assigned inside or as a input value.

**Comment by pixtur** [comment]
I looked into this and it appears that I misunderstood how the NAudio.Midi package is supposed to be used. 
I adjusted the implementation accordingly and pushed the fix to the dev branch which will be available with the next release of T3.

Thanks for pointing this out.
