### ISSUE TITLE
MIDIOutput operator is not sending NoteOff MIDI command when sendMode is set to "Note_FixedDuration"

### ISSUE THREAD

**Issue by JosebaBeristain** [tooll3/t3#385]
**Describe the bug**
MIDIOutput operator is not sending NoteOff command when sendMode is set to "Note_FixedDuration". It's suposed that this operator should send a noteOff MIDI command after the seconds defined on DurationInSecs paramenter, but this is not happening. This means that the send MIDI notes get frozen for ever.

**Please complete the following information):**
 - OS: Windows 10
 - Version: Tooll 3.9.1

**To Reproduce**
- Create a MIDIOutput operator. 
- Set the SendMode to "Notes_FixedDuration"
- Use another operator to activate the TriggerSend parameter
- Check with MIDIView (or any similar software) that note off is not sent.

**Expected behavior**
Afer triggering, one the NoteOn MIDI command is sent, the operator should send the NoteOff MIDI command after some seconds, defined in the DurationSexs parameter, but this is not happening.

**Screenshots**
https://github.com/tooll3/t3/assets/161488670/b34a33d7-a342-4a8a-b74c-9616fe5adc31

**Comment by pixtur** [comment]
Thanks for reporting. This issue has been resolved and the behavior should work as expected with the next release of T3 (v3.10)
