### ISSUE TITLE
"Redo" shortcut label under Edit is wrong

### ISSUE THREAD

**Issue by BlobbishTheArtist** [tooll3/t3#407]
**Describe the bug**
under Edit, it says the shortcut for Redo is CTRL+Y, it should be CTRL+SHIFT+Z

**To Reproduce**
1. Go to 'Edit'
2. Look at 'Redo'
4. See wrong label

**Expected behavior**
Redo shortcut label should say "CTRL+SHIFT+Z"

**Screenshots**
![image](https://github.com/tooll3/t3/assets/87548979/afd9b4fb-f6d1-4a6d-903d-13af5235da53)

**Comment by ylmrx** [comment]
fixed in #408 , thank you for the report 😺

**Comment by pixtur** [comment]
Thanks!
