### ISSUE TITLE
inconsistent PickStringPart

### ISSUE THREAD

**Issue by pixtur** [tooll3/t3#409]
Please look at the following graph:

both should have returned different results for the two indices.

![image](https://github.com/tooll3/t3/assets/1732545/3a8f4700-1c9b-4f0f-a654-a6ba094108e6)

**Comment by ylmrx** [comment]
The `RandomString` operator only return _ONE_ "word" string at a given time.
Given a single word (when set to word), `PickStringPart` will issue this word (no matter the `FragmentStart` value):

```
var moduloIndex = (startFragment + index) % _numberOfChunks;
```

so in our case `moduloIndex` will always be 0 (x % 1 = 0 , no matter the value an integer x)

I think you're confusing `RandomString` (issue a new _single_ word with each beat), and `MockStrings` (issue a collection of random words). This will behave as you intend.

**Comment by pixtur** [comment]
Thanks for looking into this. Kind of embarrassing really, considering I wrote that op.
I think its name is pretty misleading so I will rename it to something like AnimRandomString
