### ISSUE TITLE
Feature Request: Keybind/option to navigate in/out of nodes

### ISSUE THREAD

**Issue by mjtroyer** [tooll3/t3#414]
I've got RSI in both of my elbows which inflames when I double click a lot. I would really appreciate the implementation of any alternative for navigating in and out of nodes.

This was requested in the discord but it was mentioned there are issues with implementing keybinds for opening/closing an op/node. Even if there was an option when right clicking a node to 'open', it would be super helpful cutting down repetitive clicks.

Thanks so much for all the work

**Comment by newemka** [comment]
Hello, I managed to add this feature but I didn't impletement it via UserAction.cs so I will rework it and make a pull request
https://github.com/tooll3/t3/assets/3755089/c83af49a-05ba-4dec-b242-ffcf2150ec2e

**Comment by newemka** [comment]
https://github.com/tooll3/t3/pull/416

**Comment by mjtroyer** [comment]
> here is the Pull Request: #416

Thank you <3
