### ISSUE TITLE
String to value parser

### ISSUE THREAD

**Issue by 9b0** [tooll3/t3#422]
### Is your proposal related to a problem?

Missing operator to parse string to float/int values.

### Describe the solution you'd like

I need to read out values from string objects (txt/URL). I can crop a string to the desired location using the PickStringPart node, but I cannot use the received value to control parameters.

### Describe alternatives you've considered

I was trying to solve this with the 'String to Date/Time' parser, since Date/Time can be converted to floats, but the result got cumbersome, and not ideal to work with.

### Additional context

I was looking at the tryParse C# method as a solution: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/types/how-to-convert-a-string-to-a-number

**Comment by pixtur** [comment]
This has been merged and will be available in next version.
