### ISSUE TITLE
 [PointsOnImage] generates stray 45 degree line of particles

### ISSUE THREAD

**Issue by Malzbier** [tooll3/t3#427]
**Describe the bug**
[PointsOnImage] produces unexpected results resultieren in Points outside of expected image pattern.
Its placing particles randomly in a 45 degree line from the top left of the image.

**Please complete the following information):**
 - OS: Windows 10 X64  10.0.19045.0
 - Version: T3 V3.9.1
 - Graphics card and resolution :  GeForce RTX 3090  2560x1440

**To Reproduce**
1. Add [CheckerBord] node, Size : 1x Resolution : 512x512 Color A: White , Color B: Black 
2. Add [PointsOnImage] node,Count: 1000 connect [CheckerBord] to texture input
3. Add [VisualizePoints] node, Connect [PointsOnImage] output points to Points input.
4. Select  [VisualizePoints] to Observe wrongly placed particles

Example Setup:

`[{"Name":"Object","Id":"ef9f7908-2cb0-4bc8-ac70-12eba335f731","Inputs":[],"Children":[{"Id":"a2abeced-1ef0-4bed-84ef-1a5d6b3c9ed2"/*PointsOnImage*/,"SymbolId":"722e79cc-47bc-42cc-8fce-2e06f36f8caa","InputValues":[{"Id":"5c7e5e27-2eb8-4933-97cb-fc49d576d625"/*Count*/,"Type":"System.Int32","Value":1000}],"Outputs":[]},{"Id":"ca59dc3d-f073-477e-8cf4-88e7be3fab4b"/*VisualizePoints*/,"SymbolId":"37bdbafc-d14c-4b81-91c3-8f63c3b63812","InputValues":[],"Outputs":[]},{"Id":"cfdcb6cd-653f-41b5-8661-10852ac2cccf"/*CheckerBoard*/,"SymbolId":"1a411be2-1757-4019-8ce2-e29f808ed839","InputValues":[{"Id":"1192cfbe-585f-45f0-a37b-5fe78ca32d7b"/*ColorA*/,"Type":"System.Numerics.Vector4","Value":{"X":1.0,"Y":0.99999005,"Z":0.99999005,"W":1.0}},{"Id":"b08aba90-f33f-4402-bb7b-bcfc4bb624ce"/*ColorB*/,"Type":"System.Numerics.Vector4","Value":{"X":0.0,"Y":0.0,"Z":0.0,"W":1.0}},{"Id":"e367bd72-c37c-4a7f-8441-698161ba75f8"/*Scale*/,"Type":"System.Single","Value":1.0},{"Id":"63ebb6c9-e8a5-43e4-97a4-3a34ad585474"/*Resolution*/,"Type":"T3.Core.DataTypes.Vector.Int2","Value":{"X":512,"Y":512}}],"Outputs":[]}],"Connections":[{"SourceParentOrChildId":"cfdcb6cd-653f-41b5-8661-10852ac2cccf","SourceSlotId":"9dd9dbeb-b506-4d10-97b7-34feaab91f07","TargetParentOrChildId":"a2abeced-1ef0-4bed-84ef-1a5d6b3c9ed2","TargetSlotId":"5184f2ec-4f91-4dd2-9872-d9ad8d4e5d92"},{"SourceParentOrChildId":"a2abeced-1ef0-4bed-84ef-1a5d6b3c9ed2","SourceSlotId":"7c8567c9-1456-4040-ad43-4cc8a96efbaf","TargetParentOrChildId":"ca59dc3d-f073-477e-8cf4-88e7be3fab4b","TargetSlotId":"54fc4cd7-dfc3-4690-9fd1-2b555f7656d4"}]},{"Id":"ef9f7908-2cb0-4bc8-ac70-12eba335f731"/*Object*/,"InputUis":[],"SymbolChildUis":[{"ChildId":"a2abeced-1ef0-4bed-84ef-1a5d6b3c9ed2"/*PointsOnImage*/,"Position":{"X":167.67847,"Y":12.449707}},{"ChildId":"ca59dc3d-f073-477e-8cf4-88e7be3fab4b"/*VisualizePoints*/,"Style":"Expanded","Size":{"X":110.0,"Y":231.0},"Position":{"X":335.49927,"Y":0.0}},{"ChildId":"cfdcb6cd-653f-41b5-8661-10852ac2cccf"/*CheckerBoard*/,"Position":{"X":0.0,"Y":25.731934}}],"OutputUis":[]}]
`
**Expected behavior**
Particles only show up in the white areas of the provided checkerboard image

**Screenshots**
![image](https://github.com/tooll3/t3/assets/680531/3be7c8f0-5177-4ad0-9e73-ea8734a7de72)
![image](https://github.com/tooll3/t3/assets/680531/be1fcdbb-4974-4faa-bd6b-ab753d663e4e)

**Additional context**
Seems to happen on all Resolution / pattern , just harder to observer on less clear patterns like photos

**Comment by pixtur** [comment]
Thanks for reporting. There was a bug in the binary-search method. It should be fixed on dev.
I also improved many other features of the op.
