### ISSUE TITLE
Bypassed nodes are not bypassed on load

### ISSUE THREAD

**Issue by rstecca** [tooll3/t3#446]
**Describe the bug**
Nodes that are marked as bypassed still contribute to the graph when the operator is loaded.

**Please complete the following information):**
 - OS: Win11
 - Version: 3.9.1
 - Graphics card and resolution: Nvidia RTX 4070

**To Reproduce**
1. Create an empty project. Don't delete the template nodes.
2. Add a Transform node between Text and RenderTarget, set an offset (for example change Translation's Y to 0.250)
3. Select the Transform node and mark it for bypass (SHIFT+B)
4. Save
5. Close T3
6. Open T3 and load the test project.
7. See that despite the Transform is visually marked as bypassed, it still contributes to the graph.

**Expected behavior**
On load, bypassed nodes should be initialized so they are effectively bypassed.

**Screenshots**
![image](https://github.com/tooll3/t3/assets/578142/4d0c0396-ba4c-4576-b095-409bc960ec72)

**Additional context**
It doesn't seem to depend on the type of node as I tested with a few and this problem is consistent.

**Comment by pixtur** [comment]
Thanks for this excellent bug report.
I thought this issues was fixed with f329a2871d5827eb46e08a4be0f51a9bb957bd46 

I will look into this.

**Comment by pixtur** [comment]
I tried to reproduce this issue with the current dev branch and the issue appears to be fixed for the upcoming release.

**Comment by rstecca** [comment]
That's great! Looking forward to the next release!

**Comment by pixtur** [comment]
Here you go: https://github.com/tooll3/t3/releases/tag/v3.9.2
