### ISSUE TITLE
CombineMesh of two displaced QuadMeshes crashes t3

### ISSUE THREAD

**Issue by Bl4ckh34d** [tooll3/t3#448]
**Describe the bug**
When I displace two QuadMeshes by Audio and try to combine them before DrawMesh the whole program crashes.

**Please complete the following information):**
 - OS: Windows 11
 - Version: 3.9.1
 - NVIDIA GeForce RTX 3070 Ti Laptop, Resolution: 3840x1600

**To Reproduce**
1. Create two QuadMesh, Subdivide 400x50.
2. Displace the two QuadMesh with a DisplaceMeshNoise node.
3. Plug the two DisplaceMeshNoise nodes into the CombineMesh node.
4. Crash.

**Expected behavior**
Two Meshes combines visible.

**Screenshots**
![Screenshot 2024-07-01 150052](https://github.com/tooll3/t3/assets/63246613/5a74c9a3-878a-4212-aceb-f2b9e7680869)

**Comment by pixtur** [comment]
This will be fixed with 3.9.2
