### ISSUE TITLE
Program hang at Quit \ long unload (about 5 min)

### ISSUE THREAD

**Issue by ab459-code** [tooll3/t3#460]
**Describe the bug**
After pick to Quit program hang for long time (I timed it about 5 minutes), with state "Not Response". No any activity with this (CPU or HDD), just two opens windows (and processes in tray).
Running\loading and factory examples all working smooth, just fine.  I see prob only at Quit stage.

**Please complete the following information):**
 - OS:  Win10 x64
 - Version: 22h2 (Tool3 version latest v3.9.2)
 - Graphics card and resolution  GTX 1660 6gb ; 2560x1440

**To Reproduce**
1. Go to 'Project' dropdown menu
2. Click on 'Quit'

**Additional context**
Installed addition things:
Windows Graphics tools
dotnet-sdk-6.0.424-win-x64.exe
VC_redist.x64.exe

**Comment by pixtur** [comment]
That sounds very wrong. Does the installation work otherwise?

Would it be possible to share a log file saved to `.t3/logs/` ?

**Comment by ab459-code** [comment]
Hi Thomas, i sent whole folder with all logs to your email.

**Comment by pixtur** [comment]
It looks like the tooll3 email address is broken. It would be great if you could upload the file here.

**Comment by domportera** [comment]
this might be the OSC hanging thing i mentioned on discord?

**Comment by pixtur** [comment]
This should be fixed with the upcoming version.
