### ISSUE TITLE
Symbol OSCExecute in OscOutputExemple don't seem to exist

### ISSUE THREAD

**Issue by wargreen** [tooll3/t3#464]
**Describe the bug**
When opening the example of OscOutput, we can see that the graph is driven by the symbol OSCExecute.
This symbol don't seem to really exist : no parameters and can't find it for add it elsewhere.

**Please complete the following information):**
 - OS: Debian SID
 - Version: 3.9.2
 - Graphics card and resolution : R9

**To Reproduce**
1. Add OscOutput
2. Open the example
3. See the OSCExecute symbol
4. Try to add OSCExecute elsewhere

**Expected behavior**
A clear and reproducible example :)

**Screenshots**
![image](https://github.com/user-attachments/assets/7034d754-1190-43f6-bcfb-d4c9fd605993)

**Additional context**
Also tried on windows.

**Comment by pixtur** [comment]
Hi @wargreen . Thanks for your request and pointing this out.

The problem here is that "OSCExecute" is an output with a somewhat unusual name. Unfortunately it's not easily recognizable as an output node. I will look into that and improve the design.

**Comment by pixtur** [comment]
I adjusted the design of output node to make this a little bit more evident:
![image](https://github.com/user-attachments/assets/ae18a046-1022-48db-8e95-d0e57b7d228b)

**Comment by wargreen** [comment]
Thank you for this !
I can't check it now : does all the input / output have the same design ? I don't remember but it can be really cool.

**Comment by pixtur** [comment]
Not not yet. But it's a great idea. I will look into it.
